"""NyxOS PDF-ready report generator (HTML that prints to PDF)."""
from datetime import datetime


PDF_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>NyxOS Report - {case_name}</title>
<style>
@page {{ margin: 2cm; }}
body {{ font-family: 'Helvetica', Arial, sans-serif; color:#222; line-height:1.5; }}
h1 {{ color:#0b3d91; border-bottom:3px solid #0b3d91; padding-bottom:10px; }}
h2 {{ color:#0b3d91; margin-top:30px; }}
.critical {{ color:#a00; font-weight:bold; }}
.high {{ color:#d35400; font-weight:bold; }}
.medium {{ color:#b8860b; font-weight:bold; }}
.low {{ color:#2e7d32; font-weight:bold; }}
.info {{ color:#555; }}
table {{ width:100%; border-collapse:collapse; margin-top:10px; }}
th,td {{ border:1px solid #ccc; padding:8px; text-align:left; }}
th {{ background:#0b3d91; color:white; }}
pre {{ background:#f5f5f5; padding:12px; border-radius:4px; font-size:11px; overflow:auto; }}
.meta {{ color:#666; font-size:13px; }}
</style></head><body>
<h1>&#x1F6E1; NyxOS Security Report</h1>
<p class="meta">
  <b>Case:</b> {case_name} &nbsp;|&nbsp;
  <b>Generated:</b> {generated} &nbsp;|&nbsp;
  <b>Analyst:</b> {analyst}
</p>

<h2>Executive Summary</h2>
<p>
  This report covers security assessment of <b>{case_name}</b>.
  Assessment identified <b>{findings_count}</b> findings across
  <b>{assets_count}</b> assets.
  Highest risk score: <b>{max_risk}</b>.
</p>

<h2>Assets ({assets_count})</h2>
<table>
  <tr><th>Type</th><th>Identifier</th><th>Metadata</th></tr>
  {assets_rows}
</table>

<h2>Findings ({findings_count})</h2>
{findings_html}

<h2>Methodology</h2>
<p>NyxOS automated assessment using: recon (dig, whois, subfinder, whatweb),
network scanning (nmap), vulnerability matching (CVE database, nuclei),
credential analysis (hashcat patterns), and evidence capture with SHA-256 hashing.</p>

<h2>Recommendations</h2>
<ul>
  <li>Remediate critical and high severity findings first.</li>
  <li>Disable unused services; restrict exposed ports via firewall.</li>
  <li>Enforce strong authentication (no default credentials).</li>
  <li>Keep services up to date; monitor CVE feeds.</li>
  <li>Use encrypted protocols (SSH, HTTPS) instead of cleartext (telnet, FTP).</li>
</ul>

<p class="meta" style="margin-top:40px;">Generated by NyxOS &mdash; {generated}</p>
</body></html>"""


def build_pdf_html(db, case_id, analyst="NyxOS Analyst"):
    case = db.fetchone("SELECT * FROM cases WHERE id=?", (case_id,))
    if not case:
        raise ValueError(f"Case {case_id} not found")
    case_name = case["name"]

    assets = db.fetchall("SELECT * FROM assets WHERE case_id=?", (case_id,))
    findings = db.fetchall(
        "SELECT * FROM findings WHERE case_id=? ORDER BY risk_score DESC",
        (case_id,))

    assets_rows = "".join(
        f"<tr><td>{a['type']}</td><td>{a['identifier']}</td>"
        f"<td><code>{a['metadata'][:80]}</code></td></tr>"
        for a in assets) or '<tr><td colspan="3">No assets.</td></tr>'

    findings_parts = []
    max_risk = 0.0
    for f in findings:
        sev = f["severity"].lower()
        max_risk = max(max_risk, f["risk_score"] or 0)
        ev = db.fetchall("SELECT * FROM evidence WHERE finding_id=?", (f["id"],))
        ev_html = "".join(
            f"<pre>{e['type']} (sha256:{e['hash'][:16]}...)<br/>"
            f"{e['content'][:600]}</pre>"
            for e in ev
        ) or "<p><i>No evidence captured.</i></p>"

        findings_parts.append(f"""
        <div>
          <h3><span class="{sev}">[{f['severity'].upper()}]</span> {f['title']}</h3>
          <p><b>Risk Score:</b> {f['risk_score']} &nbsp;
             <b>Asset ID:</b> {f['asset_id'] or '-'} &nbsp;
             <b>Detected:</b> {f['created_at'][:19]}</p>
          {ev_html}
        </div>
        <hr/>
        """)

    findings_html = "".join(findings_parts) or "<p>No findings.</p>"

    return PDF_TEMPLATE.format(
        case_name=case_name,
        generated=datetime.utcnow().isoformat(),
        analyst=analyst,
        findings_count=len(findings),
        assets_count=len(assets),
        max_risk=max_risk,
        assets_rows=assets_rows,
        findings_html=findings_html,
    )
